
vmclone = {"Total duration of VM clones" : 33,
           "Duration of nth VM clone" : 266}
actDir = {"Duration of joining domain" : 458,
          "Duration of leabin domain" : 459,
          "Duration of CLI command" : 460,
          "Duration of SSH command" : 461}
apache = {"Apachebench measurement (per client)" : 308,
          "Apachebench measurements (average across clients)" : 309,
          "Apachebench measurements (median across requests)" : 310,
          "Apachebench measurements (max across requests)" : 465}
blackw = {"HTTP throughput" : 476,
              "HTTP throughput (mean over time)" : 477,
              "HTTP end-to-end" : 479,
              "HTTP end-to-end" : 480,
              "DNS req/sec" : 495,
              "DNS req/sec (mean over time)" : 496,
              "SSL encrypted throughput" : 483,
              "SSL encrypted throughput (mean)" : 484,
              "SSL TPS" : 486,
              "SSL TPS (mean)" : 487,
              "TCP Conn/sec" : 481,
              "TCP Conn/sec (mean)" : 482}
diskconc2 = {"Aggregate disk thoughput" : 389,
             "Disk throughput" : 390,
             "Maximum agg disk throughput" : 453,
             "Aggregate IOPS" : 454,
             "Min agg disk throughput single block-size" : 500}
lmbench = {"Simple syscall" : 41,
           "Simple read" : 42,
           "Simple write" : 43,
           "Simple stat" : 44,
           "Simple fstat" : 45,
           "Simple open/close" : 46,
           "Signal handler installation" : 47,
           "Signal handler overhead" : 48,
           "Protection fault" : 49,
           "Pipe latency" : 50,
           "Pipe bandwidth" : 66,
           "AF_UNIX sock stream latency" : 51,
           "AF_UNIX sock stream bandwidth" : 65,
           "Process fork+exit" : 52,
           "Process fork+execve" : 53,
           "Process fock+/bin/sh -c" : 54,
           "Float bogomflops" : 55,
           "Double bogomflops" : 56,
           "File /local/scratch/XXX write bandwidth" : 57,
           "Pagefaults on /local/scratch/XXX" : 58,
           "UDP latency using localhost" : 59,
           "TCP latency using localhost" : 60,
           "61 RPC/udp latency using localhost" : 61,
           "RPC/tcp latecy using localhost" : 62,
           "TCP/IP connection cost to localhost" : 63,
           "Average transfer" : 64,
           "TLB size" : 67,
           "Select on X fds" : 68,
           "Select on X TCP fds" : 69,
           "Filesystem latency (create ops per second)" : 70,
           "Filesystem latency (delete ops per second)" : 71,
           "Sock bandwidth using localhost" : 72,
           "Read bandwidth" : 73,
           "Read open2close bandwidth" : 74,
           "Mmap read bandwidth" : 75,
           "Mmap read open2close bandwidth" : 76,
           "Libc bcopy unaligned" : 77,
           "Libc bcopy aligned" : 78,
           "Memory read bandwidth" : 82,
           "Memory write bandwidth" : 84,
           "Integer op" : 90,
           "Int64 op" : 91,
           "Float op" : 92,
           "Double op" : 93,
           "Integer op parallelism" : 94,
           "Int64 op parallelism" : 95,
           "Float op parallelism" : 96,
           "Double op parallelism" : 97,
           "Steam2 latency" : 99,
           "Stream2 bandwidth" : 101} 

netThroughput = {"vm <-> bare 1vif throughput per thread" : 339,
                 "dom0 <-> bare 1nic throughput per thread" : 340,
                 "bare <-> bare 1nic thoughput per thread" : 341,
                 "vm <-> vm 1vif thoughput per thread" : 342,
                 "vm <-> vm 1vif thoughput per thread(2)" : 343,
                 "vm <-> bare 1vif thoughput sum of threads" : 344,
                 "dom0 <-> bare 1nic throughput sum of threads" : 345}

soms = {"VM clone" : vmclone,
        "Active Directory operations" : actDir,
        "Apachebench" : apache,
        "Blackwidow" : blackw,
        "Diskconc2" : diskconc2,
        "Lmbench" : lmbench,
        "Network throughput" : netThroughput}
xaxis = {"branch": 0,
         "product": 1,
         "build_number": 2,
         "build_date": 3,
         "build_tag":4,
         "job_id": 5}
somTypes = ["VM clone", "Active Directory operations", "Apachebench", "Blackwidow",
            "Diskconc2", "Lmbench", "Network throughput"]
